language: java
jdk:
- oraclejdk8
addons:
  apt:
   sources:
    - mongodb-upstart
    - sourceline: 'deb [arch=amd64] http://repo.mongodb.org/apt/ubuntu precise/mongodb-org/3.4 multiverse'
      key_url: 'https://www.mongodb.org/static/pgp/server-3.4.asc'
   packages:
    - oracle-java8-installer
    - mongodb-org-server
    - mongodb-org-shell
install: "./gradlew assemble"
before_script:
- sleep 25
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- openssl aes-256-cbc -K $encrypted_2e10550d3ce7_key -iv $encrypted_2e10550d3ce7_iv
  -in gradle.properties.enc -out gradle.properties -d
after_success:
- test $TRAVIS_BRANCH = "master" && ./gradlew uploadArchives
